### ISSUE TITLE
Home > Projekt Counter: Ist der Mix-Blend-Mode Difference einheitlich auf alle Bilder in Graustufen?

### ISSUE THREAD

**Issue by Marcel-Strauss** [orc-hfg/schaufenster#161]
Manchmal wirkt es so, als wären doch noch farbige Momente dabei. 
Bei Bio-Design-Lab in Graustufen, bei anderen Projekt wirkt es farbig. 

<img width="602" alt="Image" src="https://github.com/user-attachments/assets/c1479109-b445-4ad1-b118-a481bfcf8af3" />
<img width="480" alt="Image" src="https://github.com/user-attachments/assets/de6036b0-5044-426f-8672-5270aedefe61" />

**Comment by hannesherold** [comment]
Ja, er steht immer auf `difference` mit der Farbe Weiß. Den zusätzlichen Kontrast-Filter brauchen wir, damit er auch vor weißem Hintergrund sichtbar ist.

```css
.project_counter.projekt {
  mix-blend-mode: difference;
  filter: contrast(0.5);
  color: white;
}
```
